# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b877ccd1-0453-4d1a-a2ad-8d67403955eb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9FFC-7BDD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Additional SSDs
  fileSystems."/mnt/documents" =
    { device = "/dev/disk/by-uuid/84DA39F2DA39E0DA";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" "gid=100" "umask=022" ];  # uid=1000 is r00t user, gid=100 is users group
    };

  fileSystems."/mnt/steam" =
    { device = "/dev/disk/by-uuid/30D44061D4402B82";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" "gid=100" "umask=022" ];
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/86D21E7BD21E7023";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" "gid=100" "umask=022" ];
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/CADA2361DA2348D1";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" "gid=100" "umask=022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
