tailscale-auth-key: ENC[AES256_GCM,data:BcRbW8IAu7rLvdlEwDTiY1YCuZwM3Y9SALROtmOkg/+XGRz7Upc375VhbKkln2a7m5LRHvI5YE4Uj82H2Q==,iv:FSP7JSEAdrAL0R5UJLUQC7v/wO4VnwfcIE6/4ENPmhM=,tag:c/7utW786i+S54+9LkRqjw==,type:str]
sops:
    age:
        - recipient: age1w00vhxx5rldju9pyaj2qmmgk4lk8z7khhyt949fgqekfqxpq439su0e8cc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVGwxMDZIZ0tkWlBsVEsw
            bUVHb2Q0dnZ3dnRRV1dPRDlqTDd1REF5V1VnCnl0TW5QYVlrSExhcjRQVmpJK2ph
            TDBpV3hEYXVQamdVTkhQc3U1dEZvR2MKLS0tIHpWZ1NDd3ZnRVVTTndONXRaUEFI
            dnkrRGNzcHJ3Mm9DSHlNQ0ZDRjNWVUEKbG83BqP+52vK9gh6SvOU7KMWvO8gHXKA
            NJNQvSaWgBd2gC/wWHMYl81MslLLjzKvmp3/J2I9vZx3+I6IQP7Vdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T19:58:35Z"
    mac: ENC[AES256_GCM,data:Byt6J9qitVvkeD680WR58klTWJ6DrEmi2vYth4nVwYM2i/LHDHa9bwh0Vn0w3zFDqiE57nTXAynmgbK3HdhpjPR3RGE8XAQ/ZcJ3IdPKt70uybmENme+/7NL9nuODBXJBahtfRk7zxAv8yVzNEVvl+MXfQ6XZgvvqM0yFZ8v++4=,iv:P7vyzzBwFxHrGf31toYfiF00q624i8ODoMwBlvjfIBs=,tag:MLlR2Y8saXWQ1xc/YRphIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
