tailscale-auth-key: ENC[AES256_GCM,data:n5jm8DhO/WVkTaQOK0phEmegqR8JkHZzxyFK9HI7VGm6oQMrvytGqUkA8dyscDzR9ai3anSQ3xvI8z7DMaw=,iv:2sFVR0bQDNIvegwqpoXJeiGUsl+sM0wHvehtzeyG71M=,tag:Co9Izza+CqktzBJTNKXw/g==,type:str]
sops:
    age:
        - recipient: age1w00vhxx5rldju9pyaj2qmmgk4lk8z7khhyt949fgqekfqxpq439su0e8cc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVGwxMDZIZ0tkWlBsVEsw
            bUVHb2Q0dnZ3dnRRV1dPRDlqTDd1REF5V1VnCnl0TW5QYVlrSExhcjRQVmpJK2ph
            TDBpV3hEYXVQamdVTkhQc3U1dEZvR2MKLS0tIHpWZ1NDd3ZnRVVTTndONXRaUEFI
            dnkrRGNzcHJ3Mm9DSHlNQ0ZDRjNWVUEKbG83BqP+52vK9gh6SvOU7KMWvO8gHXKA
            NJNQvSaWgBd2gC/wWHMYl81MslLLjzKvmp3/J2I9vZx3+I6IQP7Vdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T20:53:26Z"
    mac: ENC[AES256_GCM,data:ajyzRfaUKgmdnmaMjc1bdExZyX7rngyWIYspcJxHC415KDO8s/ORxmQIL87UdOxfBWw1fX9vI1SpejeQL4F/mD8EC82xDvTmxKcRv7clK7+GVj86kh526TWdCJiElgauvh/JEp4qotLheCn1A1QQpaVtsTaYgB5VPLCtjU/0Tl4=,iv:H1pqQFbtl7jjM4HGiJ4vqoc4UspsbcS0fd4cKDO2GEs=,tag:XMlKGcvcWVPI5WWrUqRlkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
