# WinApps - Run Windows apps (Microsoft Office, Adobe, etc.) on Linux via RDP
# https://github.com/winapps-org/winapps
#
# === DEPENDENCIES ===
# - Virtualization: libvirt + virt-manager (snowfire). Or Docker/Podman.
#
# === CONFIG ===
# Edit credentials (user/pass) and winappsConfig below. SECURITY: The password
# will be in the Nix store. For sensitive setups, use a placeholder here and edit the file
# manually, or use sops-nix/agenix for encrypted secrets.
#
# === INSTALL (libvirt) ===
# 1. Create Windows VM in virt-manager (name: RDPWindows) - see docs/libvirt.md
# 2. Install Windows, enable RDP, run oem/install.bat, add RDPApps.reg
# 3. Start VM but do NOT log in: virsh start RDPWindows
# 4. Run: winapps-setup --user
# 5. Use winapps or app shortcuts from your launcher
#
# === OEM FOLDER ===
# The oem folder (RDP registry tweaks, install.bat, etc.) is auto-deployed from the
# winapps repo to ~/.config/winapps/oem when you run home-manager switch.
#
{ config, lib, pkgs, inputs, ... }:
let
  # Customize these - written to compose.yaml
  composeConfig = {
    version = "tiny11";           # Windows version: "11", "10", "tiny11", etc.
    ramSize = "4G";
    cpuCores = "4";
    diskSize = "64G";
    # groupAdd = "keep-groups";  # Uncomment for rootless podman + /dev/kvm
  };

  # Windows credentials - single source of truth for compose + winapps.conf
  credentials = {
    user = "WindowsRDP";
    pass = "123456";
  };

  # RDP / WinApps config - written to winapps.conf
  # All options from https://github.com/winapps-org/winapps#step-3-create-a-winapps-configuration-file
  winappsConfig = {
    rdpDomain = "";               # Domain (blank for local)
    rdpIp = "";                   # Blank for libvirt (auto-detect VM IP)
    vmName = "RDPWindows";        # Must match virt-manager VM name
    waFlavor = "libvirt";         # "docker" | "podman" | "libvirt" | "manual"

    # [Display & RDP]
    rdpScale = "100";             # "100" | "140" | "180"
    rdpFlags = "/cert:tofu /sound /microphone +home-drive";
    rdpFlagsNonWindows = "";      # Extra flags for app sessions (not full desktop)
    rdpFlagsWindows = "";         # Extra flags for full desktop session

    # [Paths]
    removableMedia = "/run/media"; # Path for removable devices

    # [Debug & FreeRDP]
    debug = true;
    freerdpCommand = "";          # e.g. "xfreerdp" or "xfreerdp3" (blank = auto-detect)

    # [Timeouts] (seconds)
    portTimeout = "5";            # Port check
    rdpTimeout = "30";            # RDP connection test
    appScanTimeout = "60";        # Application scan
    bootTimeout = "120";          # Windows VM boot wait

    # [Behavior]
    hidef = "on";                 # "on" | "off" - window alignment for maximized windows
    autopause = "off";            # "on" | "off" - auto-pause Windows when idle
    autopauseTime = "300";        # Idle seconds before pause (min 20, ignored if autopause off)
  };

  homeDir = config.home.homeDirectory;
  composeYaml = ''
    # For documentation: https://github.com/dockur/windows

    name: "winapps"
    volumes:
      data:
    services:
      windows:
        image: ghcr.io/dockur/windows:latest
        container_name: WinApps
        environment:
          VERSION: "${composeConfig.version}"
          RAM_SIZE: "${composeConfig.ramSize}"
          CPU_CORES: "${composeConfig.cpuCores}"
          DISK_SIZE: "${composeConfig.diskSize}"
          USERNAME: "${credentials.user}"
          PASSWORD: "${credentials.pass}"
          HOME: "${homeDir}"
        ports:
          - 8006:8006
          - 3389:3389/tcp
          - 3389:3389/udp
        cap_add:
          - NET_ADMIN
        stop_grace_period: 120s
        restart: on-failure
        volumes:
          - data:/storage
          - ${homeDir}:/shared
          - ./oem:/oem
        devices:
          - /dev/kvm
          - /dev/net/tun
  '' + lib.optionalString (composeConfig ? groupAdd) ''
        group_add:
          - ${composeConfig.groupAdd}
  '';
in
{
  home.packages = with inputs.winapps.packages.${pkgs.stdenv.hostPlatform.system}; [
    winapps
    winapps-launcher
    pkgs.freerdp  # xfreerdp - needed for WinApps RDP connections
  ];

  # Compose only used for Docker/Podman (not libvirt)
  home.file.".config/winapps/compose.yaml" = lib.mkIf (winappsConfig.waFlavor == "docker" || winappsConfig.waFlavor == "podman") {
    text = composeYaml;
  };

  # WinApps RDP config - edit winappsConfig above
  home.file.".config/winapps/winapps.conf" = {
    text = ''
      # WinApps configuration - generated by office-winapps.nix

      RDP_USER="${credentials.user}"
      RDP_PASS="${credentials.pass}"
      RDP_DOMAIN="${winappsConfig.rdpDomain}"
      RDP_IP="${winappsConfig.rdpIp}"
      VM_NAME="${winappsConfig.vmName}"
      WAFLAVOR="${winappsConfig.waFlavor}"
      RDP_SCALE="${winappsConfig.rdpScale}"
      REMOVABLE_MEDIA="${winappsConfig.removableMedia}"
      RDP_FLAGS="${winappsConfig.rdpFlags}"
      RDP_FLAGS_NON_WINDOWS="${winappsConfig.rdpFlagsNonWindows}"
      RDP_FLAGS_WINDOWS="${winappsConfig.rdpFlagsWindows}"
      DEBUG="${if winappsConfig.debug then "true" else "false"}"
      FREERDP_COMMAND="${winappsConfig.freerdpCommand}"
      PORT_TIMEOUT="${winappsConfig.portTimeout}"
      RDP_TIMEOUT="${winappsConfig.rdpTimeout}"
      APP_SCAN_TIMEOUT="${winappsConfig.appScanTimeout}"
      BOOT_TIMEOUT="${winappsConfig.bootTimeout}"
      HIDEF="${winappsConfig.hidef}"
      AUTOPAUSE="${winappsConfig.autopause}"
      AUTOPAUSE_TIME="${winappsConfig.autopauseTime}"
    '';
  };

  # Deploy oem folder from winapps repo (RDP registry tweaks, install.bat, etc.)
  home.file.".config/winapps/oem".source =
    "${builtins.fetchTarball {
      url = "https://github.com/winapps-org/winapps/archive/2dbd242649027ac1b8c44619c5f6ce3fd2e22851.tar.gz";
      sha256 = "1v9w43ldkb4b8n0bvk1whqrfd4qf5f0jylq0jx55nbn3j9qkrplj";
    }}/oem";
}
